name: Build and push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build_and_push_to_docker_hub:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Set up Docker Hub
      uses: docker/setup-buildx-action@v3
    -
      name: Build and push to Docker Hub
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/one-time-password:latest
          ${{ secrets.DOCKER_USERNAME }}/one-time-password:${{ github.sha }}
          ${{ secrets.DOCKER_USERNAME }}/one-time-password:${{ github.run_id }}
